# Generated by Django 4.2.7 on 2023-12-01 18:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaDaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_visita', models.DateField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(default='Nenhum tipo de observação.', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens_pet/')),
                ('nome', models.CharField(max_length=45)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('FEMININO', 'Feminino'), ('MASCULINO', 'Masculino')], max_length=45)),
                ('descricao_medica', models.TextField(default='Nenhum tipo de observação.', max_length=200)),
                ('castrado', models.BooleanField(default=False, help_text='Marque esta caixa se o animal for castrado.')),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('especie', models.CharField(choices=[('CACHORRO', 'Cachorro'), ('GATO', 'Gato')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('dose', models.SmallIntegerField()),
                ('idade_minima_em_semanas', models.SmallIntegerField(blank=True)),
                ('tempo_de_espera_em_dias', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vacinacao', models.DateField(default=django.utils.timezone.now)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='servicos.pet')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacinacao', to='servicos.vacina')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dias_da_semana', models.ManyToManyField(to='servicos.diadasemana')),
            ],
        ),
    ]
