# Generated by Django 4.2.7 on 2023-12-02 00:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaDaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens_pet/')),
                ('nome', models.CharField(max_length=45)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('FEMININO', 'Feminino'), ('MASCULINO', 'Masculino')], max_length=45)),
                ('castrado', models.BooleanField(default=False, help_text='Marque esta caixa se o animal for castrado.')),
                ('descricao_medica', models.TextField(default='Nenhum tipo de observação.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('especie', models.CharField(choices=[('CACHORRO', 'Cachorro'), ('GATO', 'Gato')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dias_da_semana', models.ManyToManyField(to='servicos.diadasemana')),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('dose', models.SmallIntegerField()),
                ('idade_minima_em_meses', models.SmallIntegerField(blank=True)),
                ('tempo_de_espera_em_dias', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vacinacao', models.DateField(default=django.utils.timezone.now)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='servicos.pet')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacina', to='servicos.vacina')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('servicos', models.ManyToManyField(to='servicos.servico')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='raca', to='servicos.raca'),
        ),
        migrations.AddField(
            model_name='pet',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turma', to='servicos.turma'),
        ),
    ]
