# Generated by Django 4.2.7 on 2023-11-16 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='funcionarios',
            field=models.ManyToManyField(to='usuarios.funcionario'),
        ),
        migrations.AddField(
            model_name='pet',
            name='historico_de_saude',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_de_saude', to='servicos.historicodesaude'),
        ),
        migrations.AddField(
            model_name='pet',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='raca', to='servicos.raca'),
        ),
        migrations.AddField(
            model_name='pet',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.pet'),
        ),
        migrations.AddField(
            model_name='grade',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servico'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('pet', 'servico')},
        ),
    ]
