<<<<<<< HEAD
# Generated by Django 4.2.7 on 2023-12-02 00:40
=======
# Generated by Django 4.2.7 on 2023-12-01 18:18
>>>>>>> feat/front

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
=======
            model_name='servico',
            name='funcionarios',
            field=models.ManyToManyField(to='usuarios.funcionario'),
        ),
        migrations.AddField(
            model_name='pet',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='raca', to='servicos.raca'),
        ),
        migrations.AddField(
>>>>>>> feat/front
            model_name='pet',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
