# Generated by Django 4.2.7 on 2023-12-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('servicos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='funcionario',
            field=models.ManyToManyField(to='usuarios.funcionario'),
        ),
    ]
