# Generated by Django 4.2.7 on 2023-11-16 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacinacao',
            old_name='vacinacao',
            new_name='vacina',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='historico_de_saude',
        ),
        migrations.RemoveField(
            model_name='vacinacao',
            name='historico_de_saude',
        ),
        migrations.AddField(
            model_name='pet',
            name='castrado',
            field=models.BooleanField(default=False, help_text='Marque esta caixa se o animal for castrado.'),
        ),
        migrations.AddField(
            model_name='pet',
            name='descricao_medica',
            field=models.TextField(default='Nenhum tipo de observação.', max_length=200),
        ),
        migrations.AddField(
            model_name='vacinacao',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='servicos.pet'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HistoricoDeSaude',
        ),
    ]
