# Generated by Django 4.2.7 on 2023-12-02 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_servico_funcionario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='funcionario',
            new_name='funcionarios',
        ),
    ]
