# Generated by Django 4.2.7 on 2023-11-30 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_alter_diadasemana_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicos', models.ManyToManyField(to='servicos.servico')),
            ],
        ),
        migrations.RenameField(
            model_name='vacina',
            old_name='idade_minima_em_semanas',
            new_name='idade_minima_em_meses',
        ),
        migrations.AlterField(
            model_name='vacinacao',
            name='vacina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacina', to='servicos.vacina'),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
