# Generated by Django 4.2.7 on 2023-12-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_rename_funcionario_servico_funcionarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacinacao',
            name='data_vacinacao',
        ),
        migrations.RemoveField(
            model_name='vacinacao',
            name='vacina',
        ),
        migrations.AddField(
            model_name='vacinacao',
            name='vacina',
            field=models.ManyToManyField(to='servicos.vacina'),
        ),
    ]
