# Generated by Django 4.2.7 on 2023-12-01 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_turma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='turma',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='turma', to='servicos.turma'),
            preserve_default=False,
        ),
    ]
