# Generated by Django 4.2.7 on 2023-12-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_pet_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='valor_total',
        ),
    ]
