# Generated by Django 4.2.7 on 2023-12-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0007_remove_turma_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
